id: AE33DB28B
title: 'Bestowing the Splendour of All That is Desirable: Fire Offering for the ''Neck-Pouch
  Dagger’ (Purba Gulkhukma) Cycle'
type: translation
pechas:
- I3D067889
- I89134496
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:50:43.526161
  last_modified_at: 2023-01-04 12:50:43.526183
  collections:
  - Khenchen Jigme Phuntsok Series
  - Works of Tibetan Masters
alignment_to_base:
  I3D067889/8D2D: '4723'
  I89134496/1C15: '4723'
